theme: minima
title: My Portofolio
author: [Syaban, S.Kom.]
email: [sya.ban253@admin.sma.belajar.id]
description: > # This is a description for search engines
  Portofolio digital ini menampilkan pengalaman dan bukti kerja saya sebagai Staff Tata Usaha SMA Negeri 1 Blega Bangkalan, 
  berfokus pada manajemen infrastruktur perangkat dan jaringan sekolah, kearsipan, dan efisiensi administrasi sekolah.
